### ISSUE TITLE
Add builds for the browser

### ISSUE THREAD

**Issue by vixalien** [google/transmat#24]
It's a shame that you can't even use Transmat from a CDN like UNPKG. I don't understand why you may even this for node because Transmat is a frontend library.

It may be very good indeed to have UMD builds.

(I would have personally done it and committed it, but Google libraries always have weird dependencies and I don't own a supercomputer yet)

**Comment by jtangelder** [comment]
Sorry, not an expert on this! When using build tools like webpack, node-style imports is a common pattern, but this might not be useful for all. Let me see how to add an UMD build.

**Comment by jtangelder** [comment]
Available at UNPKG at https://unpkg.com/transmat/lib/index.umd.js

**Comment by vixalien** [comment]
index.umd.min.js ? 👉👈
